import "../../sytles/globals.css";
import SelfNavbar from "@/components/navbarLogout";
import Footer from "@/components/footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
        <SelfNavbar/>
        {children}
        <Footer/>
      </>
  )
}
