import "../../sytles/globals.css";
import SelfNavbar from "@/components/navbarLogout";
import Footer from "@/components/footer";
import {getCurrentUser} from "@/lib/session";
import {UserInfo} from "@/types/user";
import {redirect} from "next/navigation";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function Layout({
                                   children,
                               }: {
    children: React.ReactNode
}) {

    return (
        <>
            <SelfNavbar/>
            {children}
            <Footer/>
        </>
    )
}
