import "../../sytles/globals.css";
import Container from "@/app/apps/navbarLogin";
import {getCurrentUser} from "@/lib/session";
import {UserInfo} from "@/types/user";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function Layout({
                                   children,
                               }: {
    children: React.ReactNode
}) {
    const user = (await getCurrentUser()) as UserInfo;

    return (
        <>
            <Container contentComponent={children} userInfo={""}/>
        </>
    )
}
