import "../../sytles/globals.css";
import Container from "@/app/apps/navbarLogin";
import {getCurrentUser} from "@/lib/session";
import {UserInfo, UseRemaining} from "@/types/user";
import {checkStatus} from "@/lib/membership/checkStatus";
import {redirect} from "next/navigation";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function Layout({
                                   children,
                               }: {
    children: React.ReactNode
}) {
    const user = (await getCurrentUser()) as UserInfo;
    const userRemain = await checkStatus(user) as UseRemaining;



    return (
        <>
            <Container contentComponent={children} userInfo={user} userRemain={userRemain}/>
        </>
    )
}
